### PR TITLE
Automatically set production flag for live environment

### PR DESCRIPTION
**Pull request by zyv**
I this that it's pretty easy to forget production flag and click can be elegantly hacked to set the right default automatically, so why not?

### CODE REVIEW

**Comment by mm-matthias** [comment]
Ich enthalte mich hier, da ich nicht tief genug in Click drin bin.

**Comment by zyv** [comment]
Hi @stohrendorf,

Thanks for following it up! Unfortunately, I couldn't get to it during the week.... :(

> Please use `DependentOptionDefault` (see https://github.com/moneymeets/ghd/blob/master/docker/ghd.py#L92).

Aha, ok, I was wondering how the description thing works, but oversaw a non-standard helper and didn't investigate any further.

I see you changed it for consistency, but I'm really wondering if you could explain what are the advantages of (1) vs. (2)?

For me the disadvantages of (1) are:

1. Non-standard / non-obvious extension to Click
2. Seems extremely complex and overengineered for the given use case

Other considerations:

1. Dependency on other options is clear from the code anyways
2. Options are evaluated in the decorator order

(2)

```python
default=lambda: get_commit_subject(click.get_current_context().params["ref"]) or "Deployed via GHD"
```

(1)

```python
class DependentOptionDefault(click.Option):
    _value_key = "_default_val"

    def __init__(self, *args, depends_on: str, **kwargs):
        self.depends_on = depends_on
        super(DependentOptionDefault, self).__init__(*args, **kwargs)

    def get_default(self, ctx):
        if not hasattr(self, self._value_key):
            arg = ctx.params[self.depends_on]
            default = self.type_cast_value(ctx, self.default(arg))
            setattr(self, self._value_key, default)
        return getattr(self, self._value_key)

    def prompt_for_value(self, ctx):
        default = self.get_default(ctx)

        # only prompt if the default value is None
        if default is None:
            return super(DependentOptionDefault, self).prompt_for_value(ctx)

        return default
```

I would rather get rid of `DependentOptionDefault` and replace it with `click.get_current_context().params[XXX]` everywhere...

At least it will be clear and obvious what / how is going on and 20 lines of code from a different file with non-standard stuff will vanish.

**Comment by zyv** [comment]
In as far as production environments are concerned: good point, but I would rather do something like this to avoid duplicating a name constant:

```diff
PRODUCTION_ENVIRONMENTS = ("live",)
- ORDERED_ENVIRONMENTS = ("dev", "test", "live")
+ ORDERED_ENVIRONMENTS = ("dev", "test") + PRODUCTION_ENVIRONMENTS
```

**Comment by stohrendorf** [comment]
The reason for adding `DependentOptionDefault` is a slightly different behaviour when prompted.

`DependentOptionDefault` version:
```
ghd deploy -r moneymeets/ghd
Ref: master
Environment (dev, test, live): live
Transient [y/N]: 
Check constraints [Y/n]: 
moneymeets/ghd@master will be deployed to live
```

lambda version:
```
ghd deploy -r moneymeets/ghd
Ref: master
Environment (dev, test, live): live
Transient [y/N]: 
Description [Deployed via GHD]: 
Check constraints [Y/n]: 
moneymeets/ghd@master will be deployed to live
```

With `DependentOptionDefault` you are not prompted for overriding the default value.

**Comment by zyv** [comment]
> With `DependentOptionDefault` you are not prompted for overriding the default value.

Ah ok, it wasn't clear to me that it was a desired behaviour... This is indeed impossible to achieve with a simple context read. I'm happy with confirming the defaults though if this helps to remove code :)

**Pull request merged**
