### PR TITLE
Fix automatic detection of commit tag names: only report exact matches

### PR DESCRIPTION
**Pull request by zyv**
... was initially quite shocked to see that I'm deploying on `dev` something, that is allegedly already `live`, but in fact was just committed...

### CODE REVIEW

**Comment by mm-matthias** [comment]
Der falsche Tag hat mich auch schon ein paar Mal irritiert.

**Comment by mm-matthias** [comment]
@stohrendorf Wie paßt dein Kommentar zu der Änderung? Das verstehe ich noch nicht ganz.

**Comment by stohrendorf** [comment]
English please, public repo here ;)

For clarification: `git describe --tags {ref}` returns something like `live/v123-10-g89abcde`, which means 10 commits since the tag live/v123. With `--exact-match`, nothing is returned, so I don't know how large the difference between the current state and the to-be-deployed state is, although one could argue that it's not optimal that you're comparing dev commits to live commits, but on the other hand you then see that live is lagging behind dev.

**Comment by mm-matthias** [comment]
@stohrendorf Does it make sense to merge this given that the new functionality explicitly lists the 10 comments that you want to see?

**Comment by zyv** [comment]
I will close this, because we are decommissioning the tool anyways and will not be using tags to track deployments at all either.

I have no strong feelings about it being one way or another, just apparently didn't pay attention to the rest of the `describe` output and was shocked to see something with **live** there, but one could argue that the current output was helpful...

**Pull request closed without merging**
